POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Testihenkilo",
    "number":"1313-1333"
}

### Test for name that's already in use
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Arto Hellas",
    "number":"1313-1333"
}

### Test for empty fields 1
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Testi",
    "number":""
}

### Test for empty fields 2
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"",
    "number":"22222"
}